apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: premium
spec:
  priority: 1
  poolRef:
    group: inference.networking.k8s.io
    name: gaie-inference-scheduling
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: standard
spec:
  priority: 0
  poolRef:
    group: inference.networking.k8s.io
    name: gaie-inference-scheduling
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: batch
spec:
  priority: -1
  poolRef:
    group: inference.networking.k8s.io
    name: gaie-inference-scheduling
