inferenceExtension:
  replicas: 1
  flags:
  image:
    # both downstream infernece-scheduler and upstream epp image can support inference-scheduling example
    ###################
    name: llm-d-inference-scheduler
    hub: quay.io/rh_ee_rsaini
    tag: odhFC-3.4Patched
    ###################
    # name: epp
    # hub: registry.k8s.io/gateway-api-inference-extension
    # tag: v1.4.0
    ###################
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "slo-flow-control-plugins.yaml"
  pluginsCustomConfig:
    slo-flow-control-plugins.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: queue-scorer
      - type: kv-cache-utilization-scorer
      - type: prefix-cache-scorer
      - type: metrics-data-source
        parameters:
          scheme: "http"
          path: "/metrics"
          insecureSkipVerify: true
      - type: model-server-protocol-metrics
      - type: slo-deadline-ordering-policy
      - type: round-robin-fairness-policy
      schedulingProfiles:
      - name: default
        plugins:
        - pluginRef: queue-scorer
          weight: 2
        - pluginRef: kv-cache-utilization-scorer
          weight: 2
        - pluginRef: prefix-cache-scorer
          weight: 3
      saturationDetector:
        queueDepthThreshold: 1
        kvCacheUtilThreshold: 0.05
      featureGates:
      - flowControl
      flowControl:
        maxBytes: 1073741824
        defaultRequestTTL: 1m
        priorityBands:
        - priority: 10
          orderingPolicyRef: fcfs-ordering-policy
          fairnessPolicyRef: round-robin-fairness-policy
        - priority: 5
          orderingPolicyRef: fcfs-ordering-policy
          fairnessPolicyRef: round-robin-fairness-policy
        - priority: 1
          orderingPolicyRef: fcfs-ordering-policy
          fairnessPolicyRef: round-robin-fairness-policy
  # Distributed tracing configuration (OpenTelemetry)
  tracing:
    enabled: false
    # otelExporterEndpoint: "http://otel-collector:4317"
    # sampling:
    #   sampler: "parentbased_traceidratio"
    #   samplerArg: "0.1"
  monitoring:
    interval: "10s"
    prometheus:
      enabled: true
      auth:
        secretName: inference-scheduling-gateway-sa-metrics-reader-secret
inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "inference-scheduling"
