router:
  epp:
    image:
      registry: quay.io/rh_ee_rsaini
      repository: llm-d-router-epp
      tag: latest
    pluginsConfigFile: "disagg-omni-config.yaml"
    pluginsCustomConfig:
      disagg-omni-config.yaml: |
        apiVersion: llm-d.ai/v1alpha1
        kind: EndpointPickerConfig
        plugins:
        - type: talker-filter
        - type: code2wav-filter
        - type: queue-scorer
        - type: running-requests-size-scorer
        - type: max-score-picker
        - type: passthrough-parser
        - type: header-routed-profile-handler
          parameters:
            headerKey: EPP-Phase
            defaultProfile: talker
        schedulingProfiles:
        - name: talker
          plugins:
          - pluginRef: talker-filter
          - pluginRef: max-score-picker
          - pluginRef: queue-scorer
            weight: 2
        - name: code2wav
          plugins:
          - pluginRef: code2wav-filter
          - pluginRef: max-score-picker
          - pluginRef: queue-scorer
            weight: 2
          - pluginRef: running-requests-size-scorer
            weight: 1
        requestHandler:
          parsers:
          - pluginRef: passthrough-parser
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/guide: "disagg-omni-serving"
